highlighter: pygments
github: [Repository metadata]
safe: false
lsi: false

gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title.html
paginate: 10
encoding: utf-8
markdown: kramdown

# author
author: 
  name: Clive Xu
  email: "clive_xc@163.com"
  link: "http://xucong.xyz"
  weibo: "http://weibo.com/clivexc"
  github: "https://github.com/clivexc"

# site info
title: Clive's blog
description: My personal blog
url: "http://xucong.xyz"
baseurl: 
rss_url: /pages/atom.xml

comments: 
  provider: uyan

active: 技术

cates: 
  - Ceph

locals: 
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
